apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-world
          image: stacksimplify/kube-helloworld:1.0.0