apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alertmanager
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  
  persistentVolumeReclaimPolicy: Delete

  hostPath:
    path: /root/data
    type: DirectoryOrCreate