apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  persistentVolumeReclaimPolicy: Retain # Delete | Recycle
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  
  hostPath:
    path: 
  
  awsElasticBlockStorage:
    volumeID: <volume-id>
    fsType: ext4