apiVersion: v1
kind: Config
current-context: my-kube-admin@my-kube-playground
clusters:
  - name: my-kube-playground
    cluster:
      certificate-authority: ca.cert
      server: https://my-kube-playground:6443

contexts:
  - name:
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      namespace: finance

users:
  - name:
    user:
      client-certificate: admin.crt
      client-key: admin.key

# kubectl config view
# kubectl config view --kubeconfig=my-custom-config
# kubectl config use-context prod-user@production