apiVersion: v1
kind: Pod
metadata:
  name: Static-Pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

ExecStart=/usr/local/bin/kubelet \
  --container-runtime-endpoint=/var/run/containerd/containerd.sock \
  --pod-manifest-path=/etc/kubernetes/manifests \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --network-plugin=cni \
  --register-node=true \
  --v=2

# -------------------------------------------------------------------------------
# kubelet.service                                                               #
# -------------------------------------------------------------------------------
# ExecStart=/usr/local/bin/kubelet \
#   --container-runtime=remote \
#   --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock \
#   --config=kubeconfig.yaml \
#   --kubeconfig=/var/lib/kubelet/kubeconfig \
#   --network-plugin=cni \
#   --register-node=true \
#   --v=2

# kubeconfig.yaml
# -------------------------------------------------------------------------------
# staticPodPath: /etc/kubernetes/manifests