apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
    app: frontend
spec:
  containers:
    - name: nginx-pod-container
      image: nginx:latest
      ports:
        - containerPort: 80